# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc1b21a5b48177682bba20125b68999ec7d0129972b86b73248ce96fd36cd693c788856cff7e3cdff42e42862e3266ecd482191181cacbcdd0f649e6889171d3

test:
  secret_key_base: e2d0ab41f8664e9fd6e9738d2791f45ab9f590f4e9f110c54ff96f60f64cce1947c69bac0dc3ad6379f3c36d58f7b907fed659f724988f22612440c80e39f0d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
